spring.application.name=backendv
debug=true
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Ticket_Marketplace?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
server.port=8085
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohammedelouaqqad55@gmail.com
spring.mail.password=ezqeogoxqjqtrdwr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true